# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: arm.medium
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Show CPU info
          command: cat /proc/cpuinfo
workflows:
  example:
    jobs:
      - test
